using System.ComponentModel;
using System.Text;

using Conductor.Core;
using Spectre.Console;
using Spectre.Console.Cli;

namespace Conductor.Commands;

public sealed class CompletionCommand : Command<CompletionCommand.Settings>
{
    public sealed class Settings : CommandSettings
    {
        [CommandArgument(0, "<SHELL>")]
        [Description("Target shell: powershell or bash")]
        public string Shell { get; init; } = "";
    }

    public override int Execute(CommandContext context, Settings settings)
    {
        var shell = settings.Shell.ToLowerInvariant();
        return shell switch
        {
            "powershell" => WritePowerShellCompletion(),
            "bash" => WriteBashCompletion(),
            _ => WriteUsageError(),
        };
    }

    private static int WritePowerShellCompletion()
    {
        Console.WriteLine(GeneratePowerShell());
        return 0;
    }

    /// <summary>Every verb <c>Program.cs</c> registers and does not hide, in one place because there
    /// used to be two: SF5 shipped <c>watch</c> and <c>ps</c> into the PowerShell list only, and the
    /// bash generator kept its own literal a hundred lines away. Both generators read this now, so a
    /// new verb is one edit — and <c>Completion_ContainsAllRegisteredVerbs_Exhaustive</c>, which scans
    /// <c>Program.cs</c> for the truth, is what catches you forgetting it.</summary>
    private const string Verbs =
        "run journey preflight face status watch watches gate log report pause resume approve kill skip inject abort " +
        "retry-stage rollback pause-after-stage goto rollover heartbeat plan tasks task new-plan note " +
        "bug init doctor audit mcp-serve mcp-observe completion chat bg ps history catalogue budget money otel spend " +
        "worktree " +
        "version update demo github";

    internal static string GeneratePowerShell()
    {
        var verbs = Verbs;
        var opts = "-p --plan --yes --force --dry-run --once --max-sessions --paused --headless --deep --full -o --output --name --repo -q --query --since --tail --no-auth-check --no-update-check";
        var auditOpts = "-p --plan --replay";
        var newPlanOpts = "-o --output --name --repo";
        var updateOpts = "-p --plan --check -y --yes";
        var watchOpts = "-p --plan --json --timeout --hook --hook-timeout --notify --poll";
        // KS2.6: `watches` takes the fleet-probe options, not `watch`'s brief options — it is a
        // machine-level listing (like `ps`), not a blocking subscription to one run.
        var psOpts = "--json --timeout --ports";
        return $$"""
            # conductor tab completion for PowerShell — generated by 'conductor completion powershell'
            # Source: conductor completion powershell | Invoke-Expression
            # Or save to a file and dot-source in $PROFILE: conductor completion powershell > conductor-completion.ps1

            Register-ArgumentCompleter -Native -CommandName conductor -ScriptBlock {
                param($wordToComplete, $commandAst, $cursorPosition)
                $verbs = @('{{verbs}}' -split ' ')
                $opts = @('{{opts}}' -split ' ')
                $auditOpts = @('{{auditOpts}}' -split ' ')
                $newPlanOpts = @('{{newPlanOpts}}' -split ' ')
                $updateOpts = @('{{updateOpts}}' -split ' ')
                $watchOpts = @('{{watchOpts}}' -split ' ')
                $psOpts = @('{{psOpts}}' -split ' ')
                $tokens = $commandAst.ToString() -split '\s+' | Where-Object { $_ }
                if ($tokens.Count -eq 1) {
                    $verbs | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
                    }
                }
                elseif ($tokens[1] -eq 'new-plan') {
                    $newPlanOpts | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterName', $_)
                    }
                }
                elseif ($tokens[1] -eq 'completion') {
                    @('powershell','bash') | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
                    }
                }
                elseif ($tokens[1] -eq 'plan') {
                    @('set','reload','add-stage','import') | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
                    }
                }
                elseif ($tokens[1] -eq 'audit') {
                    $auditOpts | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterName', $_)
                    }
                }
                elseif ($tokens[1] -eq 'update') {
                    $updateOpts | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterName', $_)
                    }
                }
                elseif ($tokens[1] -eq 'watch') {
                    $watchOpts | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterName', $_)
                    }
                }
                elseif ($tokens[1] -in @('ps','watches')) {
                    $psOpts | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterName', $_)
                    }
                }
                elseif ($tokens[1] -in @('run','journey','preflight','face','status','gate','log','report','pause','resume',
                        'approve','kill','skip','inject','abort','retry-stage','rollback','pause-after-stage',
                        'goto','rollover','heartbeat','tasks','task','note','bug','init','doctor')) {
                    $opts | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterName', $_)
                    }
                }
            }
            """;
    }

    private static int WriteBashCompletion()
    {
        Console.WriteLine(GenerateBash());
        return 0;
    }

    internal static string GenerateBash()
    {
        var verbs = Verbs;
        return $$"""
            # conductor tab completion for bash — generated by 'conductor completion bash'
            # Source: source <(conductor completion bash)

            _conductor_completion() {
                local cur prev words cword
                _init_completion || return
                COMPREPLY=()
                cur="${COMP_WORDS[COMP_CWORD]}"

                if [[ $COMP_CWORD -eq 1 ]]; then
                    COMPREPLY=($(compgen -W "{{verbs}}" -- "$cur"))
                    return
                fi
                case "${COMP_WORDS[1]}" in
                    run|journey|preflight|face|status|gate|log|report|pause|resume|approve|kill|skip|inject|abort|retry-stage|rollback|pause-after-stage|goto|rollover|heartbeat|tasks|task|note|bug|init|doctor|mcp-serve|mcp-observe|chat|bg)
                        COMPREPLY=($(compgen -W "-p --plan --yes --force --dry-run --once --max-sessions --paused --headless --deep --full -o --output --name --repo --no-auth-check --no-update-check" -- "$cur"))
                        ;;
                    watch)
                        COMPREPLY=($(compgen -W "-p --plan --json --timeout --hook --hook-timeout --notify --poll" -- "$cur"))
                        ;;
                    ps|watches)
                        COMPREPLY=($(compgen -W "--json --timeout --ports" -- "$cur"))
                        ;;
                    audit)
                        COMPREPLY=($(compgen -W "-p --plan --replay" -- "$cur"))
                        ;;
                    update)
                        COMPREPLY=($(compgen -W "-p --plan --check -y --yes" -- "$cur"))
                        ;;
                    completion)
                        COMPREPLY=($(compgen -W "powershell bash" -- "$cur"))
                        ;;
                    plan)
                        COMPREPLY=($(compgen -W "set reload add-stage import" -- "$cur"))
                        ;;
                    new-plan)
                        COMPREPLY=($(compgen -W "-o --output --name --repo" -- "$cur"))
                        ;;
                esac
            }
            complete -F _conductor_completion conductor
            """;
    }

    private static int WriteUsageError()
    {
        AnsiConsole.MarkupLine("[red]Unknown shell.[/] Valid: powershell, bash.");
        AnsiConsole.MarkupLine("Usage: conductor completion <powershell|bash>");
        return 1;
    }
}
