using System.ComponentModel;
using System.Text;

using Conductor.Core;
using Spectre.Console;
using Spectre.Console.Cli;

namespace Conductor.Commands;

public sealed class CompletionCommand : Command<CompletionCommand.Settings>
{
    public sealed class Settings : CommandSettings
    {
        [CommandArgument(0, "<SHELL>")]
        [Description("Target shell: powershell or bash")]
        public string Shell { get; init; } = "";
    }

    public override int Execute(CommandContext context, Settings settings)
    {
        var shell = settings.Shell.ToLowerInvariant();
        return shell switch
        {
            "powershell" => WritePowerShellCompletion(),
            "bash" => WriteBashCompletion(),
            _ => WriteUsageError(),
        };
    }

    private static int WritePowerShellCompletion()
    {
        Console.WriteLine(GeneratePowerShell());
        return 0;
    }

    internal static string GeneratePowerShell()
    {
        var verbs = "run journey face status gate log report pause resume approve kill skip inject abort retry-stage rollback pause-after-stage goto rollover heartbeat plan tasks task new-plan note bug init doctor audit mcp-serve completion chat bg version update demo";
        var opts = "-p --plan --yes --force --dry-run --once --max-sessions --paused --headless --deep --full -o --output --name --repo -q --query --since --tail";
        var auditOpts = "-p --plan --replay";
        var newPlanOpts = "-o --output --name --repo";
        var updateOpts = "-p --plan --check -y --yes";
        return $$"""
            # conductor tab completion for PowerShell — generated by 'conductor completion powershell'
            # Source: conductor completion powershell | Invoke-Expression
            # Or save to a file and dot-source in $PROFILE: conductor completion powershell > conductor-completion.ps1

            Register-ArgumentCompleter -Native -CommandName conductor -ScriptBlock {
                param($wordToComplete, $commandAst, $cursorPosition)
                $verbs = @('{{verbs}}' -split ' ')
                $opts = @('{{opts}}' -split ' ')
                $auditOpts = @('{{auditOpts}}' -split ' ')
                $newPlanOpts = @('{{newPlanOpts}}' -split ' ')
                $updateOpts = @('{{updateOpts}}' -split ' ')
                $tokens = $commandAst.ToString() -split '\s+' | Where-Object { $_ }
                if ($tokens.Count -eq 1) {
                    $verbs | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
                    }
                }
                elseif ($tokens[1] -eq 'new-plan') {
                    $newPlanOpts | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterName', $_)
                    }
                }
                elseif ($tokens[1] -eq 'completion') {
                    @('powershell','bash') | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
                    }
                }
                elseif ($tokens[1] -eq 'plan') {
                    @('set','reload','add-stage','import') | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
                    }
                }
                elseif ($tokens[1] -eq 'audit') {
                    $auditOpts | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterName', $_)
                    }
                }
                elseif ($tokens[1] -eq 'update') {
                    $updateOpts | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterName', $_)
                    }
                }
                elseif ($tokens[1] -in @('run','journey','face','status','gate','log','report','pause','resume',
                        'approve','kill','skip','inject','abort','retry-stage','rollback','pause-after-stage',
                        'goto','rollover','heartbeat','tasks','task','note','bug','init','doctor')) {
                    $opts | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterName', $_)
                    }
                }
            }
            """;
    }

    private static int WriteBashCompletion()
    {
        Console.WriteLine(GenerateBash());
        return 0;
    }

    internal static string GenerateBash()
    {
        return """
            # conductor tab completion for bash — generated by 'conductor completion bash'
            # Source: source <(conductor completion bash)

            _conductor_completion() {
                local cur prev words cword
                _init_completion || return
                COMPREPLY=()
                cur="${COMP_WORDS[COMP_CWORD]}"

                if [[ $COMP_CWORD -eq 1 ]]; then
                    COMPREPLY=($(compgen -W "run journey face status gate log report audit mcp-serve pause resume approve kill skip inject abort retry-stage rollback pause-after-stage goto rollover heartbeat plan tasks task new-plan note bug init doctor completion chat bg version update demo" -- "$cur"))
                    return
                fi
                case "${COMP_WORDS[1]}" in
                    run|journey|face|status|gate|log|report|pause|resume|approve|kill|skip|inject|abort|retry-stage|rollback|pause-after-stage|goto|rollover|heartbeat|tasks|task|note|bug|init|doctor|mcp-serve|chat|bg)
                        COMPREPLY=($(compgen -W "-p --plan --yes --force --dry-run --once --max-sessions --paused --headless --deep --full -o --output --name --repo" -- "$cur"))
                        ;;
                    audit)
                        COMPREPLY=($(compgen -W "-p --plan --replay" -- "$cur"))
                        ;;
                    update)
                        COMPREPLY=($(compgen -W "-p --plan --check -y --yes" -- "$cur"))
                        ;;
                    completion)
                        COMPREPLY=($(compgen -W "powershell bash" -- "$cur"))
                        ;;
                    plan)
                        COMPREPLY=($(compgen -W "set reload add-stage import" -- "$cur"))
                        ;;
                    new-plan)
                        COMPREPLY=($(compgen -W "-o --output --name --repo" -- "$cur"))
                        ;;
                esac
            }
            complete -F _conductor_completion conductor
            """;
    }

    private static int WriteUsageError()
    {
        AnsiConsole.MarkupLine("[red]Unknown shell.[/] Valid: powershell, bash.");
        AnsiConsole.MarkupLine("Usage: conductor completion <powershell|bash>");
        return 1;
    }
}
