using System.Globalization;
using System.Text;

namespace Conductor.Core.Release;

/// <summary>
/// CH4.4 — the owner runbook, generated from the preflight's own measurements instead of written
/// from scratch by a session.
///
/// <para><b>Why this exists.</b> <c>.conductor/evidence/KS12/ks12-3-owner-runbook.md</c> and its DV7
/// successor were hand-written twice, in the same shape, and the second one's first finding was that
/// the first one had not been carried out — six of its seven acts went unperformed, and nothing
/// noticed, because a document cannot check itself. The acts are already enumerated in code
/// (<see cref="ReleasePerform.MechanicalOrder"/> and <see cref="ReleasePerform.OwnerOrder"/>) and
/// already measured (<see cref="ReleasePreflight"/>). What was missing was the projection.</para>
///
/// <para><b>It is a projection, not a template.</b> Every line below comes from a
/// <see cref="ReleaseCheck"/> or a <see cref="ReleaseAct"/> the same two verbs produce; the verdicts
/// are <see cref="ReleasePreflight.Verdict"/> and <see cref="ReleasePerform.Verdict"/> themselves,
/// not restatements of them. Nothing here can drift from what the engine would do, because there is
/// nothing here that is not what the engine would do.</para>
///
/// <para><b>Pure.</b> No clock, no git, no network — the timestamp is an input. A document that
/// reached for the wall clock could not be asserted against, and this one has to be: the property
/// that matters is that it names EVERY act, and that is a test, not a habit.</para>
/// </summary>
public static class ReleaseRunbook
{
    /// <summary>The whole document, as markdown.</summary>
    public static string Render(RunbookFacts facts)
    {
        ArgumentNullException.ThrowIfNull(facts);
        var sb = new StringBuilder();
        var tag = facts.Tag is { Length: > 0 } t ? t.TrimStart('v', 'V') : null;

        Head(sb, facts, tag);
        Preconditions(sb, facts);
        Mechanical(sb, facts, tag);
        Owner(sb, facts);
        Order(sb, facts, tag);
        Foot(sb);
        return sb.ToString();
    }

    private static void Head(StringBuilder sb, RunbookFacts facts, string? tag)
    {
        sb.Append("# ").Append(Or(facts.PlanName, "this era")).Append(" — the era-close").Append('\n').Append('\n');
        sb.Append("**Generated by `conductor release runbook` at ").Append(Or(facts.GeneratedUtc, "an unrecorded time"))
          .Append(".** Nothing in this document was performed.").Append('\n');
        sb.Append("Every line below is the output of the probes `conductor release preflight` runs and the planner\n")
          .Append("`conductor release perform` uses, rendered — so a line that disagrees with the tree means this\n")
          .Append("document is stale. Regenerate it; never edit it, and never carry a claim forward from the last one.\n\n");

        sb.Append("| | |").Append('\n').Append("| --- | --- |").Append('\n');
        Row(sb, "repo", Code(facts.Repo));
        Row(sb, "merge", Code(Or(facts.Branch, "?")) + " → " + Code(Or(facts.BaseBranch, "master")));
        Row(sb, "release", tag is null ? "**unnamed** — the version number is yours, and everything mechanical takes it as input" : Code("v" + tag));
        Row(sb, "installed engine", Code(Or(facts.InstalledEngine, "unknown")));
        sb.Append('\n');

        sb.Append("## The verdict").Append('\n').Append('\n');
        sb.Append("- preconditions — **").Append(ReleasePreflight.Verdict(facts.Checks)).Append("**  ")
          .Append("(`release preflight` exits ").Append(Int(ReleasePreflight.ExitCode(facts.Checks))).Append(")").Append('\n');
        sb.Append("- acts — **").Append(ReleasePerform.Verdict(facts.Acts, dryRun: true)).Append("**  ")
          .Append("(`release perform` exits ").Append(Int(ReleasePerform.ExitCode(facts.Acts))).Append(")").Append('\n').Append('\n');
        // Said once, here, because it is the sentence a reader is most likely to get backwards.
        sb.Append("Exit **2** is what a finished era-close looks like: nothing red, and the acts that are yours still\n")
          .Append("standing where they always stand. A **0** would mean this engine believed it had done your job too.\n\n");
    }

    private static void Preconditions(StringBuilder sb, RunbookFacts facts)
    {
        sb.Append("## 1. The preconditions, measured").Append('\n').Append('\n');
        if (facts.Checks.Count == 0)
        {
            sb.Append("_Nothing was measured._").Append('\n').Append('\n');
            return;
        }

        sb.Append("| | check | what was measured |").Append('\n').Append("| --- | --- | --- |").Append('\n');
        foreach (var check in facts.Checks)
            sb.Append("| ").Append(CheckMark(check.State)).Append(" | `").Append(check.Name).Append("` | ")
              .Append(Cell(check.Headline)).Append(" |").Append('\n');
        sb.Append('\n');

        foreach (var check in facts.Checks.Where(c => c.Detail.Count > 0))
        {
            sb.Append("**").Append(check.Name).Append("** — ").Append(check.Headline).Append('\n').Append('\n');
            foreach (var line in check.Detail) sb.Append("- ").Append(Line(line)).Append('\n');
            sb.Append('\n');
        }
    }

    private static void Mechanical(StringBuilder sb, RunbookFacts facts, string? tag)
    {
        sb.Append("## 2. What the engine performs").Append('\n').Append('\n');
        sb.Append("One command, four acts, each landing as its own commit so the era-close is reviewable an act at\n")
          .Append("a time. Ordered, and it stops at the first refusal rather than performing the rest on a half-done\n")
          .Append("sequence. Drop `--yes` to rehearse it.").Append('\n').Append('\n');
        sb.Append("```\n").Append(PerformCommand(tag)).Append('\n').Append("```\n\n");
        Acts(sb, facts.Acts.Where(a => a.Kind == ReleaseAct.Mechanical), "No mechanical act is declared.");
    }

    private static void Owner(StringBuilder sb, RunbookFacts facts)
    {
        sb.Append("## 3. What is yours").Append('\n').Append('\n');
        sb.Append("Named on every run, whatever the state, each with the command you type. None of these is ever\n")
          .Append("reported as done or as nothing: an act that needs a person cannot be allowed to read like one that\n")
          .Append("has been handled. That mistake is the whole reason this document is generated.").Append('\n').Append('\n');
        // Anything the engine emits that is neither mechanical nor owner still appears — a bucket
        // nothing falls out of. Silence is the failure mode being engineered away here.
        Acts(sb, facts.Acts.Where(a => a.Kind != ReleaseAct.Mechanical), "No owner act is declared, which cannot be right — report it.");
    }

    private static void Acts(StringBuilder sb, IEnumerable<ReleaseAct> acts, string ifEmpty)
    {
        var any = false;
        foreach (var act in acts)
        {
            any = true;
            sb.Append("### ").Append(act.Name).Append(" — ").Append(ActMark(act.State)).Append('\n').Append('\n');
            sb.Append(Cell(act.Headline)).Append('\n').Append('\n');
            foreach (var line in act.Detail) sb.Append("- ").Append(Line(line)).Append('\n');
            if (act.Detail.Count > 0) sb.Append('\n');
        }
        if (!any) sb.Append("_").Append(ifEmpty).Append("_").Append('\n').Append('\n');
    }

    private static void Order(StringBuilder sb, RunbookFacts facts, string? tag)
    {
        sb.Append("## 4. The order").Append('\n').Append('\n');
        var n = 1;
        sb.Append(Int(n++)).Append(". `").Append(PerformCommand(tag)).Append("` — ")
          .Append(string.Join(", ", facts.Acts.Where(a => a.Kind == ReleaseAct.Mechanical).Select(a => a.Name)))
          .Append('\n');
        foreach (var act in facts.Acts.Where(a => a.Kind != ReleaseAct.Mechanical))
        {
            sb.Append(Int(n++)).Append(". **").Append(act.Name).Append("** — ").Append(Cell(act.Headline));
            if (act.Detail.FirstOrDefault(IsCommand) is { } command) sb.Append("  ·  ").Append(Code(command));
            sb.Append('\n');
        }
        sb.Append('\n');
    }

    private static void Foot(StringBuilder sb) =>
        sb.Append("---").Append('\n').Append('\n')
          .Append("Nothing was merged, tagged, moved, installed or pushed to produce this document. `release runbook`\n")
          .Append("measures and renders; `release perform --yes` is the only verb here that changes the tree, and it\n")
          .Append("stops at every act above that is yours.").Append('\n');

    private static string PerformCommand(string? tag) =>
        "conductor release perform --tag " + (tag ?? "<x.y.z>") + " --yes";

    /// <summary>GREEN / RED / YOURS, spelled rather than glyphed: this document is read in a terminal,
    /// in a diff and on a phone, and a tick is the first thing to survive none of them.</summary>
    private static string CheckMark(string state) => state switch
    {
        ReleaseCheck.Ok => "**GREEN**",
        ReleaseCheck.Owner => "**YOURS**",
        _ => "**RED**",
    };

    private static string ActMark(string state) => state switch
    {
        ReleaseAct.Ready => "**will run**",
        ReleaseAct.Done => "**done**",
        ReleaseAct.Nothing => "**already true**",
        ReleaseAct.Stopped => "**YOURS**",
        ReleaseAct.Failed => "**FAILED**",
        _ => "**REFUSED**",
    };

    /// <summary>A detail line that IS a command, as opposed to a sentence that happens to open with
    /// one. Measured on the rig: "tools/install.ps1 stops the courier at step 0 and puts it back on
    /// the new engine …" begins with a command token and is prose, and code-spanning it made a
    /// paragraph unreadable. Two further conditions settle it — a line that already carries a
    /// backtick was written as markdown by whoever wrote the act and is left exactly as it is, and a
    /// line long enough to be a sentence is a sentence.</summary>
    private static bool IsCommand(string line) =>
        line.Length <= 90
        && !line.Contains('`', StringComparison.Ordinal)
        && (line.StartsWith("git ", StringComparison.Ordinal)
            || line.StartsWith("conductor ", StringComparison.Ordinal)
            || line.StartsWith("dotnet ", StringComparison.Ordinal)
            || line.StartsWith("tools/", StringComparison.Ordinal)
            || line.StartsWith("sh tools/", StringComparison.Ordinal)
            || line.StartsWith("gh ", StringComparison.Ordinal));

    private static string Line(string text) => IsCommand(text) ? Code(text) : Cell(text);

    /// <summary>A cell that cannot break the table it is in. A measured headline carries whatever the
    /// machine said, and a stray pipe from a path or a git message would silently eat the column
    /// after it.</summary>
    private static string Cell(string text) => (text ?? "").Replace("|", "\\|", StringComparison.Ordinal).Trim();

    private static string Code(string text) => "`" + (text ?? "").Replace("`", "'", StringComparison.Ordinal).Trim() + "`";

    private static string Or(string? text, string fallback) => string.IsNullOrWhiteSpace(text) ? fallback : text.Trim();

    private static string Int(int n) => n.ToString(CultureInfo.InvariantCulture);

    private static void Row(StringBuilder sb, string key, string value) =>
        sb.Append("| ").Append(key).Append(" | ").Append(value).Append(" |").Append('\n');
}

/// <summary>CH4.4 — everything the runbook renders, and nothing it goes and finds for itself. The
/// timestamp is a string rather than a <c>DateTime</c> so the document is byte-identical for the
/// same inputs: a generated artifact that cannot be diffed against itself is a generated artifact
/// nobody checks.</summary>
public sealed record RunbookFacts(
    string PlanName,
    string Repo,
    string Branch,
    string BaseBranch,
    string? Tag,
    string InstalledEngine,
    string GeneratedUtc,
    IReadOnlyList<ReleaseCheck> Checks,
    IReadOnlyList<ReleaseAct> Acts);
