using System.Text.Json;

using Conductor.Core.Integrations;
using Conductor.Core.Integrations.Messaging;
using Conductor.Models;

namespace Conductor.Tests;

/// <summary>
/// KS11.2's other two exits — CHAPAR CH-2: the per-chat profile block, and the two ways it is
/// allowed to be wrong.
///
/// <para>Back-compat here means byte-identical, not "close enough": the fifteen KS11.1 goldens were
/// generated by an engine that had never heard of a profile, from a plan carrying only
/// <c>allowedChatIds</c>, and they are never regenerated. This file pins the same claim at the level
/// the goldens cannot see — the resolved target list itself, in order.</para>
///
/// <para>And the refusal. An unknown profile string is the one input where guessing has a direction:
/// read as admin, a typo hands an outsider the steering wheel. So it fails plan load by name, the
/// way an unknown <c>github.board</c> does, and <see cref="An_unknown_profile_fails_plan_load_by_name"/>
/// drives that through the real <c>PlanConfig.Load</c> on a file rather than the model in memory.</para>
/// </summary>
public sealed class KS11_2ChatProfileConfigTests : IDisposable
{
    private readonly string _dir;

    public KS11_2ChatProfileConfigTests()
    {
        _dir = Path.Combine(Path.GetTempPath(), $"conductor-ks11c-{Guid.NewGuid():N}");
        Directory.CreateDirectory(_dir);
        File.WriteAllText(Path.Combine(_dir, "TRACKER.md"), "# Rig\n\n## Checkpoints\n");
    }

    public void Dispose()
    {
        try { TestTemp.DeleteTree(_dir); } catch (Exception) { }
    }

    // ────────────────────────── back-compat, pinned ──────────────────────────

    /// <summary>The old shape, unchanged: ids in the order the plan wrote them, every one an admin.
    /// This is what <c>Targets</c> returned before the chats block existed.</summary>
    [Fact]
    public void An_old_shape_plan_resolves_to_its_own_ids_in_order_all_admin()
    {
        var cfg = new TelegramConfig { AllowedChatIds = { "99205495", "-100123456", "77" } };

        Assert.Equal(
            [new ChatTarget("99205495", ChatProfile.Admin),
             new ChatTarget("-100123456", ChatProfile.Admin),
             new ChatTarget("77", ChatProfile.Admin)],
            TelegramService.ResolveTargets(cfg));
        Assert.Equal(3, cfg.ChatCount);
    }

    /// <summary>Neither block: silent, exactly as today. A bot with nobody to talk to is a no-op
    /// fan-out, not an error.</summary>
    [Fact]
    public void A_plan_with_neither_block_serves_nobody()
    {
        Assert.Empty(TelegramService.ResolveTargets(new TelegramConfig()));
        Assert.Empty(TelegramService.ResolveTargets(null));
        Assert.Equal(0, new TelegramConfig().ChatCount);
    }

    /// <summary>CH-2's shape, read from the JSON a plan actually carries — not a hand-built model,
    /// because the thing that breaks silently is the deserialiser's key name.</summary>
    [Fact]
    public void The_chats_block_parses_from_plan_json_and_carries_its_profiles()
    {
        var cfg = JsonSerializer.Deserialize<TelegramConfig>(
            """
            {
              "chats": [
                { "chatId": "99205495",   "profile": "admin"    },
                { "chatId": "-100123456", "profile": "observer" }
              ]
            }
            """,
            new JsonSerializerOptions { PropertyNameCaseInsensitive = true })!;

        Assert.Null(cfg.ProfileRefusal());
        Assert.Equal(
            [new ChatTarget("99205495", ChatProfile.Admin),
             new ChatTarget("-100123456", ChatProfile.Observer)],
            TelegramService.ResolveTargets(cfg));
    }

    /// <summary>Both blocks at once — an owner adding a stakeholder to a plan that already had a
    /// chat list. The named chat keeps the profile it was given; the leftover stays admin, which is
    /// what it already was.</summary>
    [Fact]
    public void The_chats_block_wins_for_ids_it_names_and_the_rest_stay_admin()
    {
        var cfg = new TelegramConfig
        {
            AllowedChatIds = { "99205495", "-100123456" },
            Chats = { new TelegramChatEntry { ChatId = "-100123456", Profile = "observer" } },
        };

        Assert.Equal(
            [new ChatTarget("-100123456", ChatProfile.Observer),
             new ChatTarget("99205495", ChatProfile.Admin)],
            TelegramService.ResolveTargets(cfg));
        Assert.Equal(2, cfg.ChatCount);
    }

    /// <summary>An omitted profile is admin — the profile every chat has had until now. Only an
    /// UNREADABLE one is refused; a plan that simply lists its chats is not being asked to learn a
    /// new vocabulary.</summary>
    [Fact]
    public void An_omitted_profile_reads_as_admin()
    {
        var cfg = new TelegramConfig { Chats = { new TelegramChatEntry { ChatId = "77" } } };

        Assert.Null(cfg.ProfileRefusal());
        Assert.Equal([new ChatTarget("77", ChatProfile.Admin)], TelegramService.ResolveTargets(cfg));
    }

    /// <summary>Readiness counts chats, not <c>allowedChatIds</c>. Before KS11.2 this number came
    /// from the old list alone, so a plan that configured its chats the new way reported
    /// "push-only to nobody" while delivering perfectly.</summary>
    [Fact]
    public void Readiness_counts_chats_configured_the_new_way()
    {
        var cfg = new TelegramConfig
        {
            Chats = { new TelegramChatEntry { ChatId = "-100123456", Profile = "observer" } },
        };

        Assert.True(TelegramReadiness.WillDeliver(
            hasBlock: true, hasToken: true, allowedChatIds: cfg.ChatCount, started: true));
    }

    // ────────────────────────── refused by name, at load ──────────────────────────

    /// <summary>The exit: a profile string the engine cannot read stops the run at plan load, names
    /// the offending value, and names the legal ones. Driven through <c>PlanConfig.Load</c> on a
    /// real file — the path a run actually takes.</summary>
    [Fact]
    public void An_unknown_profile_fails_plan_load_by_name()
    {
        var path = WritePlan("""
              "telegram": { "chats": [ { "chatId": "-100123456", "profile": "viewer" } ] },
            """);

        var ex = Assert.Throws<InvalidOperationException>(() => PlanConfig.Load(path));

        Assert.Contains("'viewer'", ex.Message, StringComparison.Ordinal);
        Assert.Contains("-100123456", ex.Message, StringComparison.Ordinal);
        Assert.Contains("'admin' or 'observer'", ex.Message, StringComparison.Ordinal);
    }

    /// <summary>And the same plan with a profile it CAN read loads — otherwise the test above would
    /// pass on any plan that happened to be invalid for some other reason.</summary>
    [Fact]
    public void The_same_plan_with_a_known_profile_loads()
    {
        var path = WritePlan("""
              "telegram": { "chats": [ { "chatId": "-100123456", "profile": "observer" } ] },
            """);

        var plan = PlanConfig.Load(path);

        Assert.Equal([new ChatTarget("-100123456", ChatProfile.Observer)],
            TelegramService.ResolveTargets(plan.Telegram));
    }

    /// <summary>Every way of getting the block wrong that is worth a distinct sentence. Case and
    /// surrounding space are fine — a plan is hand-written JSON — and everything else is refused.</summary>
    [Theory]
    [InlineData("ADMIN", null)]
    [InlineData("  observer  ", null)]
    [InlineData("Observer", null)]
    [InlineData("owner", "'owner'")]
    [InlineData("", "empty profile")]
    [InlineData("admin,observer", "'admin,observer'")]
    public void Profile_strings_are_read_or_refused_but_never_guessed(string profile, string? expectedInRefusal)
    {
        var cfg = new TelegramConfig
        {
            Chats = { new TelegramChatEntry { ChatId = "77", Profile = profile } },
        };

        var refusal = cfg.ProfileRefusal();
        if (expectedInRefusal == null)
        {
            Assert.Null(refusal);
            return;
        }

        Assert.NotNull(refusal);
        Assert.Contains(expectedInRefusal, refusal, StringComparison.Ordinal);

        // Refused, so it never resolves — a chat the plan got wrong is a chat that hears nothing,
        // never a chat quietly promoted to admin.
        Assert.Empty(TelegramService.ResolveTargets(cfg));
    }

    /// <summary>A chats entry with no id is the other way to write a block that cannot be obeyed.</summary>
    [Fact]
    public void A_chats_entry_with_no_id_is_refused()
    {
        var cfg = new TelegramConfig { Chats = { new TelegramChatEntry { Profile = "observer" } } };

        Assert.Contains("no chatId", cfg.ProfileRefusal() ?? "", StringComparison.Ordinal);
    }

    private string WritePlan(string telegramBlock)
    {
        var path = Path.Combine(_dir, "conductor.plan.json");
        File.WriteAllText(path, $$"""
            {
              "version": "1.0",
              "name": "Rig",
              "repo": {{JsonSerializer.Serialize(_dir)}},
              "tracker": "TRACKER.md",
            {{telegramBlock}}
              "agent": { "command": "echo", "args": ["{prompt}"] },
              "stages": [ { "id": "Z1", "title": "The seam", "sessions": 1 } ]
            }
            """);
        return path;
    }
}
